version: '3.9'

services:
  nestjs:
    container_name: nestjs_dev
    image: nestjs-api-dev:1.0.0
    env_file:
      - .env-dev
    environment:
      - DB_HOST=postgres
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - nesjs-network

networks:
  nesjs-network:
